# Query Name: StudyGWASCredibleSetsQuery
# Entity Type: study
# Description:
# Retrieves GWAS credible sets for a study including study details lead
#  variants fine-mapping statistics and posterior probabilities. Uses batch
#  pagination.
# Variables: studyId: String!, size: Int!, index: Int!
# Pagination Behavior: Paginated (batch: 500/page default)
# Notes:
# Query successfully tested with GCST90002357, returned count=1514 GWAS
#  credible sets.
#
# Last Updated: 2025-11-21
query StudyGWASCredibleSetsQuery($studyId: String!, $size: Int!, $index: Int!) {
  # Return a Study
  study(studyId: $studyId) {
    # The study identifier
    id
    # Credible sets
    credibleSets(page: { size: $size, index: $index }) {
      count
      rows {
        studyLocusId
        variant {
          id
          chromosome
          position
          referenceAllele
          alternateAllele
        }
        pValueMantissa
        pValueExponent
        beta
        locus {
          count
        }
        finemappingMethod
        confidence
        l2GPredictions(page: { size: 1, index: 0 }) {
          rows {
            # Target
            target {
              # Open Targets target id
              id
              # HGNC approved symbol
              approvedSymbol
            }
            score
          }
        }
      }
    }
  }
}
