# Query Name: VariantPharmacogenomicsSummary
# Entity Type: variant
# Description:
# Retrieves summary of pharmacogenomics data for a variant. Used to determine
#  if the pharmacogenomics section should be displayed.
# Variables: variantId: String!
# Pagination Behavior: Full results
# Notes:
# Query successfully tested with 19_44908822_C_T (APOE rs7412), returns
#  pharmacogenomics summary.
#
# Last Updated: 2025-11-21
query VariantPharmacogenomicsSummary($variantId: String!) {
  # Return a Variant
  variant(variantId: $variantId) {
    # Pharmoacogenomics
    pharmacogenomics {
      isDirectTarget
    }
  }
}
