# Query Name: DrugKnownDrugsSummaryQuery
# Entity Type: drug
# Description:
# Retrieves summary counts of known drug applications including total count
#  unique targets and unique diseases
# Variables: chemblId: String!
# Pagination Behavior: Full results
# Notes:
# Query successfully tested with CHEMBL1201585 (TRASTUZUMAB), returned
#  count=239 uniqueTargets=1 uniqueDiseases=102.
#
# Last Updated: 2025-11-21
query DrugKnownDrugsSummaryQuery($chemblId: String!) {
  # Return a drug
  drug(chemblId: $chemblId) {
    # Open Targets molecule id
    id
    # Curated Clinical trial records and and post-marketing package inserts with a known mechanism of action
    knownDrugs {
      # Total number of entries
      count
      # Total unique known mechanism of action targetsTotal unique known mechanism of action targets
      uniqueTargets
      # Total unique diseases or phenotypes
      uniqueDiseases
    }
  }
}
