# Query Name: DrugBibliographyQuery
# Entity Type: drug
# Description:
# Retrieves literature occurrence counts for a drug showing total publications
#  mentioning the drug
# Variables: chemblId: String!
# Pagination Behavior: Full results
# Notes:
# Query successfully tested with CHEMBL1201585 (TRASTUZUMAB), returned
#  count=5256 publications.
#
# Last Updated: 2025-11-21
query DrugBibliographyQuery($id: String!) {
  # Return a drug
  drug(chemblId: $id) {
    # Open Targets molecule id
    id
    # Return the list of publications that mention the main entity, alone or in combination with other entities
    literatureOcurrences {
      count
      filteredCount
    }
  }
}
