# Query Name: DrugPharmacogenomicsQuery
# Entity Type: drug
# Description:
# Fetches pharmacogenomics (PharmGKB) clinical annotations for a drug
#  including drug response phenotypes genotypes associated drugs variant
#  annotations with effect descriptions confidence levels and supporting
#  literature.
# Variables: chemblId: String!
# Pagination Behavior: Full results
# Notes:
# Query successfully tested with CHEMBL1201585 (TRASTUZUMAB), returns
#  pharmacogenomics data.
#
# Last Updated: 2025-11-21
query DrugPharmacogenomicsQuery($chemblId: String!) {
  # Return a drug
  drug(chemblId: $chemblId) {
    # Open Targets molecule id
    id
    # Pharmoacogenomics
    pharmacogenomics {
      variantAnnotation {
        # Entity affected by the effect.
        entity
        # Allele observed effect.
        effect
        # Type of effect.
        effectType
        # Summary of the impact of the allele on the drug response.
        effectDescription
        # PMID of the supporting publication.
        literature
        # Allele directionality of the effect.
        directionality
        # Allele or genotype in the base case.
        baseAlleleOrGenotype
        # Allele or genotype in the comparison case.
        comparisonAlleleOrGenotype
      }
      variantRsId
      genotypeId
      variantFunctionalConsequence {
        id
        label
      }
      # Target entity
      target {
        # Open Targets target id
        id
        # HGNC approved symbol
        approvedSymbol
      }
      haplotypeId
      haplotypeFromSourceId
      isDirectTarget
      phenotypeFromSourceId
      genotypeAnnotationText
      phenotypeText
      pgxCategory
      evidenceLevel
      studyId
      literature
    }
  }
}
