# Query Name: DiseaseKnownDrugsSummary
# Entity Type: disease
# Description:
# Retrieves summary counts of known drugs for a disease including total count
#  unique drugs and unique targets
# Variables: efoId: String!
# Pagination Behavior: Full results
# Notes:
# Query successfully tested with EFO_0000685 (rheumatoid arthritis), returned
#  count=1370 uniqueDrugs=256 uniqueTargets=243.
#
# Last Updated: 2025-11-21
query DiseaseKnownDrugsSummary($efoId: String!) {
  # Return a Disease
  disease(efoId: $efoId) {
    # Clinical precedence for investigational or approved drugs indicated for disease and curated mechanism of action
    knownDrugs {
      # Total number of entries
      count
      # Total unique drugs/molecules
      uniqueDrugs
      # Total unique known mechanism of action targetsTotal unique known mechanism of action targets
      uniqueTargets
    }
  }
}
