# Query Name: IMPCSummaryQuery
# Entity Type: evidence
# Description:
# Retrieves evidence count from International Mouse Phenotyping Consortium
#  datasource for target-disease associations
# Variables: efoId: String!, ensgId: String!
# Pagination Behavior: Full results
# Notes:
# Summary query using size: 0 to return only count. Successfully tested with
#  EFO_0000685 and ENSG00000157764.
#
# Last Updated: 2025-11-21
query IMPCSummaryQuery($efoId: String!, $ensgId: String!) {
  # Return a Disease
  disease(efoId: $efoId) {
    # Open Targets disease id
    id
    # The complete list of all possible datasources
    impc: evidences(
      ensemblIds: [$ensgId]
      enableIndirect: true
      datasourceIds: ["impc"]
      size: 0
    ) {
      count
    }
  }
}
