# Query Name: UniprotVariantsSummaryQuery
# Entity Type: evidence
# Description:
# Retrieves evidence count from UniProt Variants datasource for target-disease
#  associations
# Variables: ensgId: String!, efoId: String!
# Pagination Behavior: Full results
# Notes:
# Summary query using size: 0 to return only count. Successfully tested with
#  EFO_0000685 and ENSG00000157764.
#
# Last Updated: 2025-11-21
query UniprotVariantsSummaryQuery($ensgId: String!, $efoId: String!) {
  # Return a Disease
  disease(efoId: $efoId) {
    # Open Targets disease id
    id
    # The complete list of all possible datasources
    uniprotVariantsSummary: evidences(
      ensemblIds: [$ensgId]
      enableIndirect: true
      datasourceIds: ["uniprot_variants"]
      size: 0
    ) {
      count
    }
  }
}
